repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    namespace: default
    chart: bitnami/nginx
    version: "13.2.17"  # adjust to your desired chart version
    values:
      - image:
          tag: "latest"
      - ingress:
          enabled: false
      - service:
          type: ClusterIP
          port: 80
